modLoader = "javafml"
loaderVersion = "0"
issueTrackerURL = "${mod_issue_url}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
displayURL = "${mod_display_url}"
description = '''${mod_description}'''
logoFile = "icon.png"
logoBlur = false

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "0"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "0"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "valkyrienskies"
mandatory = true
versionRange = "0"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "cloth_config"
mandatory = true
versionRange = "0"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "the_vmod"
mandatory = true
versionRange = "0"
ordering = "NONE"
side = "BOTH"
